Update minutes to include till decades
poswalsameer/Leetcost pull request #1
Opened 2024-11-26 17:34 UTC by Abhinavpatra

2024-11-26 19:01 UTC, poswalsameer requested changes

2024-11-26 19:01 UTC, poswalsameer commented on leetcost/src/app/stats/page.tsx
> +    hours: Math.floor((minutes % (60 * 24)) / 60),
Decades, years, and months are not required. Days, hours and minutes will work.

2024-11-26 19:01 UTC, poswalsameer commented on leetcost/src/app/stats/page.tsx
> +                  Time wasted: <span className="text-orange-400 font-bold">{formatTime(totalTime)}</span>
It would be really nice if you could show the time like this - `X hours / Y days / Z minutes`. Let me know if you face any issues.

2024-11-27 13:45 UTC, Abhinavpatra commented on leetcost/src/app/stats/page.tsx
> +                  Time wasted: <span className="text-orange-400 font-bold">{formatTime(totalTime)}</span>
so in pure minutes or hours or in only days and so on

2024-11-27 18:49 UTC, poswalsameer commented on leetcost/src/app/stats/page.tsx
> +                  Time wasted: <span className="text-orange-400 font-bold">{formatTime(totalTime)}</span>
> so in pure minutes or hours or in only days and so on

Right now it is just showing minutes only.

But you can do this - `X days/Y hours/Z minutes` in place of X mins only. Hope you got my point. Nothing much to, just a basic time conversion and all set!

2024-11-28 12:04 UTC, Abhinavpatra commented
yep, got it, makes sense vrna it will look too overblown, i have made the changes, let me know if there are any issues with it, regards.

2024-11-28 16:02 UTC, merged

2024-11-30 16:46 UTC, Abhinavpatra commented
will definitely do that from next time, thanks!